export const INITIAL_POSTS = [
  {
    id: 'post-1',
    author: {
      name: 'Dr. Ramesh Hegde',
      handle: 'ramesh_blr',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      badge: 'Verified Resident (18+)',
      ward: 'Ward 151 - Koramangala 4th Block',
      karma: 420
    },
    localityId: 'koramangala',
    localityName: 'Koramangala',
    wardNumber: 'Ward 151',
    departmentId: 'BBMP',
    departmentName: 'BBMP Roads & Infrastructure',
    ticketId: 'BBMP-2026-9821',
    title: 'Severe pothole crater on 80 Feet Road near Sony World Signal causing vehicle damage',
    body: 'There is a massive 2-foot wide pothole right before the Sony World Signal intersection on 80 Feet Road. Multiple two-wheeler riders skidded yesterday during evening rain. Requesting @BBMP_Commissioner and ward engineer to take emergency action.',
    image: 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&auto=format&fit=crop&q=80',
    afterImage: null,
    createdAt: '25 mins ago',
    timestamp: Date.now() - 25 * 60 * 1000,
    status: 'IN_PROGRESS',
    officialUpdate: 'BBMP Assistant Executive Engineer assigned. Asphalt repair team scheduled for tonight 11:30 PM.',
    amplifies: 142,
    agreedCount: 89,
    hasAmplified: false,
    hasAgreed: false,
    aiSafetyScore: 99,
    aiCategoryConfidence: 'High (Road Hazard / Pothole)',
    aiModerationPassed: true,
    severity: 'High Hazard',
    comments: [
      {
        id: 'c1',
        author: 'Priya Narayanan',
        handle: 'priya_kora',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        text: 'I lost my tire alignment on this exact spot on Tuesday! Upvoted for fast BBMP escalation.',
        createdAt: '15 mins ago',
        isOfficial: false
      },
      {
        id: 'c2',
        author: 'BBMP Helpdesk Official',
        handle: 'bbmp_official',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        text: 'Grievance ticket #BBMP-2026-9821 acknowledged. Ward 151 engineer is on site inspect.',
        createdAt: '8 mins ago',
        isOfficial: true
      }
    ]
  },
  {
    id: 'post-2',
    author: {
      name: 'Ananya Sharma',
      handle: 'ananya_techie',
      avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
      badge: 'Verified Resident (18+)',
      ward: 'Ward 80 - Indiranagar',
      karma: 290
    },
    localityId: 'indiranagar',
    localityName: 'Indiranagar',
    wardNumber: 'Ward 80',
    departmentId: 'BESCOM',
    departmentName: 'BESCOM (Electricity)',
    ticketId: 'BESCOM-2026-4412',
    title: 'Dangling high-voltage power cable over 12th Main footpath near Starbucks',
    body: 'Spotted live dangling wires touching tree branches on 12th Main Road, Indiranagar. During windy weather, it creates sparks. Pedestrians and morning joggers are in danger. BESCOM helpline alerted, tagging here for public awareness.',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&auto=format&fit=crop&q=80',
    afterImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&auto=format&fit=crop&q=80',
    createdAt: '2 hours ago',
    timestamp: Date.now() - 120 * 60 * 1000,
    status: 'RESOLVED',
    officialUpdate: 'BESCOM East Sub-division lineman insulated and re-routed cable. Resolved at 9:45 AM today.',
    amplifies: 215,
    agreedCount: 134,
    hasAmplified: true,
    hasAgreed: true,
    aiSafetyScore: 98,
    aiCategoryConfidence: 'Critical (Electrical Hazard)',
    aiModerationPassed: true,
    severity: 'Critical Safety',
    comments: [
      {
        id: 'c3',
        author: 'Vijay Kumar (BESCOM Lineman)',
        handle: 'bescom_e4',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
        text: 'Work completed. High tension lead secured with weather-proof conduit.',
        createdAt: '45 mins ago',
        isOfficial: true
      }
    ]
  },
  {
    id: 'post-3',
    author: {
      name: 'Kavitha Rao',
      handle: 'kavitha_hsr',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      badge: 'Verified Resident (18+)',
      ward: 'Ward 174 - HSR Layout',
      karma: 510
    },
    localityId: 'hsr-layout',
    localityName: 'HSR Layout',
    wardNumber: 'Ward 174',
    departmentId: 'BWSSB',
    departmentName: 'BWSSB (Water & Sewerage)',
    ticketId: 'BWSSB-2026-1092',
    title: 'Drinking water pipeline burst on 27th Main, Sector 1 - Water flooding streets',
    body: 'Fresh Cauvery water is being wasted at an alarming rate since 6 AM today due to a ruptured underground pipe near Agara junction. Lakhs of liters flowing down storm drains while residences have zero pressure.',
    image: 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800&auto=format&fit=crop&q=80',
    afterImage: null,
    createdAt: '3 hours ago',
    timestamp: Date.now() - 180 * 60 * 1000,
    status: 'ACKNOWLEDGED',
    officialUpdate: 'BWSSB South team dispatched valve operator to shut off mains for emergency weld repair.',
    amplifies: 310,
    agreedCount: 198,
    hasAmplified: false,
    hasAgreed: false,
    aiSafetyScore: 100,
    aiCategoryConfidence: 'High (Water Utility Burst)',
    aiModerationPassed: true,
    severity: 'High Waste',
    comments: []
  },
  {
    id: 'post-4',
    author: {
      name: 'Suresh Gowda',
      handle: 'suresh_whitefield',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      badge: 'Verified Resident (18+)',
      ward: 'Ward 84 - Whitefield',
      karma: 180
    },
    localityId: 'whitefield',
    localityName: 'Whitefield',
    wardNumber: 'Ward 84',
    departmentId: 'BBMP_SOLID_WASTE',
    departmentName: 'BBMP Solid Waste Management',
    ticketId: 'BBMP-2026-7734',
    title: 'Illegal commercial garbage dumping near ECC Road corner lot',
    body: 'Commercial eateries dumping plastic bags and food waste every midnight on ECC Road. Stench is unbearable and stray dogs are tearing packets. Need CCTV surveillance and dry-waste collection compactor.',
    image: 'https://images.unsplash.com/photo-1605600659873-d808a13e4d2a?w=800&auto=format&fit=crop&q=80',
    afterImage: null,
    createdAt: '5 hours ago',
    timestamp: Date.now() - 300 * 60 * 1000,
    status: 'REPORTED',
    officialUpdate: 'Forwarded to Mahadevapura Solid Waste Health Inspector.',
    amplifies: 87,
    agreedCount: 45,
    hasAmplified: false,
    hasAgreed: false,
    aiSafetyScore: 97,
    aiCategoryConfidence: 'Medium (Sanitation / Garbage)',
    aiModerationPassed: true,
    severity: 'Health Hazard',
    comments: []
  },
  {
    id: 'post-5',
    author: {
      name: 'Deepak Mohan',
      handle: 'deepak_jayanagar',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      badge: 'Verified Resident (18+)',
      ward: 'Ward 177 - Jayanagar',
      ward: 'Ward 177 - Jayanagar 4th Block',
      karma: 640
    },
    localityId: 'jayanagar',
    localityName: 'Jayanagar',
    wardNumber: 'Ward 177',
    departmentId: 'BTP',
    departmentName: 'Bengaluru Traffic Police (BTP)',
    ticketId: 'BTP-2026-3021',
    title: 'Traffic signal at 11th Main Jayanagar 4th Block malfunctioning (showing both Green & Red)',
    body: 'Confusing signal at 11th Main intersection causing near-miss collisions during peak school commute hours. Both pedestrians and drivers are confused. Requesting BTP traffic engineer reset.',
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&auto=format&fit=crop&q=80',
    afterImage: null,
    createdAt: '6 hours ago',
    timestamp: Date.now() - 360 * 60 * 1000,
    status: 'IN_PROGRESS',
    officialUpdate: 'BTP Jayanagar Traffic Police deployed manual traffic constable while tech repair team resets controller.',
    amplifies: 178,
    agreedCount: 112,
    hasAmplified: false,
    hasAgreed: false,
    aiSafetyScore: 99,
    aiCategoryConfidence: 'High (Traffic Safety)',
    aiModerationPassed: true,
    severity: 'Traffic Risk',
    comments: []
  },
  {
    id: 'post-6',
    author: {
      name: 'Sunita Menon',
      handle: 'sunita_malleswaram',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      badge: 'Verified Resident (18+)',
      ward: 'Ward 65 - Malleshwaram',
      karma: 390
    },
    localityId: 'malleshwaram',
    localityName: 'Malleshwaram',
    wardNumber: 'Ward 65',
    departmentId: 'BBMP',
    departmentName: 'BBMP Roads & Infrastructure',
    ticketId: 'BBMP-2026-1144',
    title: 'Heritage tree branch hanging dangerously low over Margosa Road 8th Cross',
    body: 'A heavy rain-weakened branch is split and dangling just 7 feet above the road. Needs immediate trimming before it falls on electric cables or vehicles.',
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&auto=format&fit=crop&q=80',
    afterImage: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=800&auto=format&fit=crop&q=80',
    createdAt: '1 day ago',
    timestamp: Date.now() - 24 * 60 * 60 * 1000,
    status: 'RESOLVED',
    officialUpdate: 'BBMP Forest Wing cleared fallen branch safely with zero damage to wires.',
    amplifies: 195,
    agreedCount: 120,
    hasAmplified: false,
    hasAgreed: false,
    aiSafetyScore: 100,
    aiModerationPassed: true,
    severity: 'Moderate',
    comments: []
  }
];
